[package]
name = "node-zero"
version = "0.1.0"
authors = ["wuuzw <29149346+wuuzw@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.62"
nix = "0.19.1"
tempfile = "3.2.0"
flate2 = "1.0.20"
tar = "0.4.33"
curl = "0.4.34"
is-root = "0.1.2"
dialoguer = "0.7.1"
